//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Expense.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.MonthIncome = new HashSet<MonthIncome>();
            this.Receipt = new HashSet<Receipt>();
        }
    
        public string UserID { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<MonthIncome> MonthIncome { get; set; }
        public virtual ICollection<Receipt> Receipt { get; set; }
    }
}
